"""add manager_id

Revision ID: 3a5dd2b3ea9e
Revises: 568dab8b3197
Create Date: 2023-12-10 15:21:15.804214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5dd2b3ea9e'
down_revision: Union[str, None] = '568dab8b3197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('manager_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'organizations', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'manager_id')
    # ### end Alembic commands ###
